name: recipex_app
description: Recipe app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  http: ^0.13.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  font_awesome_flutter: ^10.3.0
  lottie: ^2.3.2
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_switch: ^0.3.2
  logger: ^1.1.0
  firebase_auth_desktop: ^1.0.2
  firebase_core_desktop: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_core_platform_interface: 4.5.1 
  flutter_launcher_icons: ^0.12.0
  firebase_database: ^9.1.7
  cloud_firestore: ^3.5.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/food/

  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Medium.otf
        - asset: fonts/Satoshi-Regular.otf
        - asset: fonts/Satoshi-Bold.otf
    - family: LobsterTwo
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Cabinet
      fonts:
        - asset: fonts/CabinetGrotesk-Regular.otf
        - asset: fonts/CabinetGrotesk-Medium.otf
        - asset: fonts/CabinetGrotesk-Bold.otf
    - family: Karma
      fonts:
        - asset: fonts/Karma-Medium.otf
        - asset: fonts/Karma-Regular.otf

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
