name: recipex_app
description: Recipe app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  http: ^0.13.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/not_found.png

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-VariableFont_wght.ttf
    - family: Quincy
      fonts:
        - asset: fonts/Fontspring-DEMO-quincycf-regular.otf
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
