name: recipex_app
description: Recipe app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  http: ^0.13.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.3.0
  lottie: ^1.4.2
  smooth_page_indicator: ^1.0.0+2
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_switch: ^0.3.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/intro/

  fonts:
    - family: Lora
      fonts:
        - asset: fonts/Lora-VariableFont_wght.ttf
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Medium.otf
    - family: ClashGrotesk
      fonts:
        - asset: fonts/ClashGrotesk-Medium.otf
    - family: LobsterTwo
      fonts:
        - asset: fonts/LobsterTwo-Regular.ttf
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
